services:

  memcached:
    container_name: BE_193480_memcached
    image: memcached:latest
    networks:
      - prestashop_network

  ps:
    image: billypl/be_188898_prestashop-v1
    command: /bin/bash -c "a2enmod ssl && apache2-foreground"
    depends_on:
      - db
    ports:
      - 18889:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_188898
      DB_USER: root
      DB_PASSWD: student
      PS_DEV_MODE: 1
    deploy:
      placement:
        constraints:
          - "node.hostname == student-swarm01" # for easy execing
      resources:
        limits:
          cpus: "2.0"
          memory: "3G"
        reservations:
          cpus: "1.0"
          memory: "512M"
    networks:
      - admin-mysql_default
      - prestashop_network

networks:
  prestashop_network:
  admin-mysql_default:
    external: true
