services:
  ps:
    image: billypl/be_188898_prestashop-v1
    restart: unless-stopped
    command: /bin/bash -c "a2enmod ssl && apache2-foreground"
    depends_on:
      - db
    ports:
      - 18889:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_188898
      DB_USER: root
      DB_PASSWD: student
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
    networks:
      - admin-mysql_default
      - prestashop_network

networks:
  prestashop_network:
  admin-mysql_default:
    external: true
