name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
      - test/github_actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_SECRET }}
        password: ${{ secrets.DOCKERHUB_USERNAME }}


    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./prestashop
        file: ./prestashop/Dockerfile
        tags: prestashop/prestashop:1.7.8.11


    - name: Test Docker image locally
      run: |
        docker pull prestashop/prestashop:1.7.8.11
        echo "Docker image built and pushed successfully"
